# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listing_photos', verbose_name='Upload a photo')),
                ('location', models.CharField(choices=[('Denver', 'Denver'), ('Sherrills', 'Sherrills'), ('Mooresville', 'Mooresville'), ('Davidson', 'Davidson'), ('Cornelius', 'Cornelius'), ('Huntersville', 'Huntersville')], max_length=15)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
