# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20160624_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='listing',
            name='pick_category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='cat_choice', to='main_app.Category'),
            preserve_default=False,
        ),
    ]
