# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20160624_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category'),
        ),
    ]
