# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20160624_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub',
            new_name='choose_main',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='main',
            new_name='new_category',
        ),
    ]
