# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20160625_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='traderprofile',
            name='preferred_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Listing'),
        ),
    ]
