# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20160625_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Location'),
        ),
        migrations.AlterField(
            model_name='traderprofile',
            name='preferred_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Location'),
        ),
    ]
