# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20160625_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traderprofile',
            old_name='logo',
            new_name='photo',
        ),
    ]
