# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20160625_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traderprofile',
            old_name='photo',
            new_name='logo',
        ),
        migrations.AlterField(
            model_name='traderprofile',
            name='trader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
