# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20160625_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='city_choice',
        ),
        migrations.RenameField(
            model_name='traderprofile',
            old_name='trader',
            new_name='user',
        ),
    ]
